### PR TITLE
Text Classification Notebook

### PR DESCRIPTION
**Pull request by luisquintanilla**

### CODE REVIEW

**Comment by luisquintanilla** [comment]
Ready for review when you get a chance @michaelgsharp @JakeRadMSFT

**Comment by JakeRadMSFT** [comment]
Is this a REF or an E2E?
I'd recommend renaming the file to one of these:

REF-Text Classification with Yelp Dataset.ipynb
E2E-Text Classification with Yelp Dataset.ipynb

**Comment by JakeRadMSFT** [comment]
Please add to https://github.com/dotnet/csharp-notebooks/blob/main/machine-learning/shorturl_bulk.csv once you have name picked out and I'll add the short url.

**Comment by JakeRadMSFT** [comment]
https://ntbk.io/ml-e2e-text-classification-api

**Review by JakeRadMSFT — APPROVED** [review]

**Pull request merged**
