### PR TITLE
Edit pass of notebooks

### PR DESCRIPTION
**Pull request by beccamc**
Spellcheck etc. of notebooks. Mainly fixed verb agreement issues

### CODE REVIEW

**Comment by beccamc** [comment]
Yeah this is ready! It's random markdown updates

**Comment by beccamc** [comment]
@luisquintanilla Does it seem like the metadata changes are wrong? Do I need to re-run them to make sure everything looks good

**Comment by luisquintanilla** [comment]
> @luisquintanilla Does it seem like the metadata changes are wrong? Do I need to re-run them to make sure everything looks good

I don't think so. The diff experience could be better so it's hard to identify the changes to the markdown. Metadata changes I think happen automatically anytime you open notebooks. Let me give it another look.

**Review by luisquintanilla — COMMENTED** [review]
Thanks @beccamc for doing this edit pass. Looks great. The E2E Classification Iris and E2E Forecasting with Regression notebooks still show the metadata changes.

**Pull request merged**
