### PR TITLE
Fix ML.NET Notebook Errors

### PR DESCRIPTION
**Pull request by JakeRadMSFT**
Having the error outputs saved in the Notebooks was causing some of them not to load in GitHub. This PR fixes the errors.

Fixes this issue:
image

### CODE REVIEW

**Comment by JakeRadMSFT** [comment]
@luisquintanilla @LittleLittleCloud @zewditu @beccamc 

Thoughts? I'm a bit conflicted on having vs not having outputs.

**Comment by LittleLittleCloud** [comment]
+1 on having output...

What character causes the output becomes invalid

**Comment by JakeRadMSFT** [comment]
> +1 on having output...
> 
> What character causes the output becomes invalid

I don't think it's actually an issue with Notebook... I think it's a bug with whatever is parsing the Notebook and generating the html/display.

Might be related to:
https://github.com/dotnet/interactive/issues/1990

**Comment by JakeRadMSFT** [comment]
> > +1 on having output...
> > What character causes the output becomes invalid
> 
> I don't think it's actually an issue with Notebook... I think it's a bug with whatever is parsing the Notebook and generating the html/display.
> 
> Might be related to: [dotnet/interactive#1990](https://github.com/dotnet/interactive/issues/1990)

I think we have two issues:

- Our save doesn't always work on ctrl+s in Visual Studio
- GitHub doesn't like when there are 'error' outputs.

**Review by luisquintanilla — APPROVED** [review]
Looks good to me.

**Pull request merged**
